### ISSUE TITLE
Error reusing Sqlite Parameters

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/Microsoft.Data.Sqlite#239] opened 2016-03-21 08:57 UTC
When I send in a single command with multiple statements, it seems to have trouble reusing the parameters across all of the statements.

Error message: 
System.InvalidOperationException: Must add values for the following parameters: @FirstName, @MiddleName, @LastName, @Title, @ManagerKey, @EmployeeKey

Command text: 
```sql
UPDATE Employee SET [FirstName] = @FirstName, [MiddleName] = @MiddleName, [LastName] = @LastName, [Title] = @Title, [ManagerKey] = @ManagerKey WHERE [EmployeeKey] = @EmployeeKey;
INSERT OR IGNORE INTO Employee ([EmployeeKey], [FirstName], [MiddleName], [LastName], [Title], [ManagerKey], [UpdatedDate]) VALUES (@EmployeeKey, @FirstName, @MiddleName, @LastName, @Title, @ManagerKey, @UpdatedDate); 
 SELECT [EmployeeKey], [FirstName], [MiddleName], [LastName], [Title], [ManagerKey], [CreatedDate], [UpdatedDate] FROM Employee WHERE EmployeeKey = CASE WHEN @EmployeeKey IS NULL OR @EmployeeKey = 0 THEN last_insert_rowid() ELSE @EmployeeKey END;
```
Parameters:
    @EmployeeKey: DBNull
    @FirstName: Tom
    @MiddleName: DBNull
    @LastName: Jones
    @Title: President
    @ManagerKey: DBNull
    @EmployeeKey: DBNull
    @FirstName: Tom
    @MiddleName: DBNull
    @LastName: Jones
    @Title: President
    @ManagerKey: DBNull
    @UpdatedDate: DBNull

***

This test passes when using System.Data.SQLite.

**Comment by natemcmaster** [comment] 2016-03-21 16:32
Are you setting parameter values to CLR null e.g. `param.Value = null;`? If so, try using `DBNull` instead: `param.Value = DBNull.Value;`. (See #200 )

**Comment by Grauenwolf** [comment] 2016-03-21 18:31
Yep, I'm using DBNull.Value here.

-----Original Message-----

**Comment by natemcmaster** [comment] 2016-03-31 17:33
@Grauenwolf I couldn't reproduce on my own. Could you provide a standalone that produces the error? Please include the version of Microsoft.Data.Sqlite you are using.

**Comment by divega** [comment] 2016-04-01 22:33
At first glance this doesn't seem to be a ship stopper for RC2, so moving to RTM milestone.

**Comment by Grauenwolf** [comment] 2016-04-02 00:05
Heck, it may be fixed in RC2. I'm on the latest release on Nuget, which is RC1.

Also, I'm sorry I haven't got your reproduction sample ready yet.

Jonathan 

-----Original Message-----

**Comment by natemcmaster** [comment] 2016-05-18 23:18
@Grauenwolf I'm closing since we haven't heard back from you. If you can reproduce this with RC2 code (which is out on NuGet.org now), please let me know and we can reopen.

**Closed by natemcmaster** 2016-05-18 23:18 UTC
Labels: investigation-needed

**Comment by Grauenwolf** [comment] 2016-05-19 02:26
Sorry I don't have a repro that I can share. But I can confirm that the issue doesn't exist in RC2. Thank you.
