### ISSUE TITLE
NullReferenceException when trying to use SqliteConnection

### ISSUE THREAD

**Issue by Flavien** [aspnet/Microsoft.Data.Sqlite#119] opened 2015-08-24 13:48 UTC
I'm getting a lot of issues with trying to make sure sqlite3.dll gets loaded properly, and on some occasions, I am even getting a NullReferenceException from the library, which is probably a bug. Stacktrace below:

```
System.AggregateException occurred
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at OpenChain.Sqlite.SqliteTransactionStore..ctor(String filename) in D:\path\SqliteTransactionStore.cs:line 29
  InnerException: 
       HResult=-2146233036
       Message=The type initializer for 'Microsoft.Data.Sqlite.Interop.NativeMethods' threw an exception.
       Source=Microsoft.Data.Sqlite
       TypeName=Microsoft.Data.Sqlite.Interop.NativeMethods
       StackTrace:
            at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
            at Microsoft.Data.Sqlite.SqliteConnection.Open()
            at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
       InnerException: 
            HResult=-2147467261
            Message=Object reference not set to an instance of an object.
            Source=Microsoft.Data.Sqlite
            StackTrace:
                 at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
            InnerException: 
```

**Comment by Flavien** [comment] 2015-08-24 13:56
Also, is it normal [here](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/01012ca936700eb5d55c22b3481a75750e37ecd5/src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs#L75) that you return true from `TryLoad` without actually loading the library?

**Comment by bricelam** [comment] 2015-08-24 15:35
What type of project are you using? ASP.NET 5?

> Also, is it normal here that you return true from TryLoad without actually loading the library?

Yes. If the native library is in a location that *should* be handled by the runtime, we let it do its thing.

**Comment by bricelam** [comment] 2015-08-24 15:36
It looks like you may be using a different version of DNX than Microsoft.Data.Sqlite is compiled against.

**Comment by Flavien** [comment] 2015-08-24 16:06
Thanks. And is it supposed to work on 64 bits runtimes? If so, where to find the 64 bits binaries for sqlite3?

**Comment by bricelam** [comment] 2015-08-24 16:17
It should work if you provide your own 64-bit build of sqlite3.dll. Unfortunately, an official one isn't available on their downloads page. There's talk of them providing a NuGet package for the native library with more target platforms. As soon as it's available, we'll start depending on it from our package and get out of the business of redistributing SQLite.

**Comment by natemcmaster** [comment] 2015-09-17 20:46
@Flavien are you still experiencing this issue with the most recent version? 

Possible duplicate of #138

**Comment by Flavien** [comment] 2015-09-18 23:25
@natemcmaster I worked around it somehow. I don't remember exactly how, but I think I was running the 64 bits DNX with the x86 sqlite (or vice versa).

**Comment by natemcmaster** [comment] 2015-09-18 23:26
Ok. Closing then. Reopen if the issue resurfaces.

**Comment by Flavien** [comment] 2015-10-18 16:54
Actually, I still in beta-8 get this unless I create a ``x86`` folder with ``sqlite3.dll`` in it.

I'm using ``dnx-coreclr-win-x86.1.0.0-beta8``.

**Comment by divega** [comment] 2015-10-18 17:55
@bricelam @natemcmaster anything we still need to do  here, at least to throw a better exception or has this been addressed post beta8?

**Comment by MJomaa** [comment] 2015-10-19 03:00
@Flavien I'm actually using SQLite for two x64 coreclr projects on a debian machine and with beta8 it works without any extra hassles here. (Not sure if x86 is even available for linux coreclr tho)
So you might be right with the x86 dependency(?)  problem.

**Comment by Flavien** [comment] 2015-10-19 09:51
@MJomaa Yes, my issue is on Windows.

**Comment by natemcmaster** [comment] 2015-10-19 16:16
@Flavien I haven't seen this error before in my testing or dev work. Can you post a sample to reproduce the issue?

**Comment by bricelam** [comment] 2015-10-19 16:36
You might be hitting #134

**Comment by Flavien** [comment] 2015-10-19 18:04
The repro is pretty straightforward:

```
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            SqliteConnection connection = new SqliteConnection(new SqliteConnectionStringBuilder() { DataSource = "data.db" }.ToString());
            connection.OpenAsync().Wait();
        }
        public void ConfigureServices(IServiceCollection services)
        {
        }
        
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
        }
    }
```

@bricelam I'm not using packages.config, so it looks like it's different.

**Comment by bricelam** [comment] 2015-10-20 00:16
Is this after publishing? It could be aspnet/dnx#2850

**Comment by Flavien** [comment] 2015-10-20 01:47
@bricelam No, even when running from Visual Studio in debug mode.

**Comment by natemcmaster** [comment] 2015-10-20 23:57
@Flavien I still can't get a repro with your sample. Can you create an entire project (please include project.lock.json) that reproduces? Also, does this reproduce when running your application from the command line in addition to VS?

**Comment by Flavien** [comment] 2015-10-21 01:32
Here is [a repro](https://onedrive.live.com/redir?resid=40C180873D8ECEE1!115841&authkey=!AEq0J71y6-aZrco&ithint=file%2czip). Yes it also reproduces from the command line (``dnx web``).

**Comment by natemcmaster** [comment] 2015-10-22 19:34
Thanks for the repro. This is a bug. The source of the problem: NativeMethods.cs: line 41. There is a bug in DNX which means in the following code, `library` can be null.

```c#
var library = CallContextServiceLocator
                    .Locator
                    .ServiceProvider
                    .GetRequiredService<ILibraryManager>()
                    .GetLibrary(typeof(NativeMethods).GetTypeInfo().Assembly.GetName().Name);
```

**Comment by natemcmaster** [comment] 2015-10-22 19:35
Should be fixed with https://github.com/aspnet/Microsoft.Data.Sqlite/issues/128.

**Comment by Flavien** [comment] 2015-10-22 21:53
Ok, thanks for looking at this Nate. So this will be fixed in rc1?

**Comment by natemcmaster** [comment] 2015-10-22 22:43
@Flavien yes. I am closing as a duplicate of #128. Reopen if this appears again in rc1.

**Closed by natemcmaster** 2015-10-22 22:43 UTC
Labels: bug
