### ISSUE TITLE
Concurrency issues; possibly support connection pooling or setting default timeout

### ISSUE THREAD

**Issue by gingters** [aspnet/Microsoft.Data.Sqlite#222] opened 2016-01-28 09:36 UTC
When you have two threads that SELECT some data and then INSERT or UPDATE a row on the same table on the same time, a "Database is locked" error is thrown.

This happens on Windows as well as on Mac OS X (was not yet tested on linux).

My approach would be to solve this by enabling connection pooling (which Microsoft.Data.Sqlite does not support) or possibly set a larger command timeout (which Microsoft.Data.Sqlite does not support on the connection string or on the connection itself). Since EF owns the actual command its not possible to set another timeout value there, too.

Please find attached a project that reproduced this issue :
[Sqlite.Repro.zip](https://github.com/aspnet/Microsoft.Data.Sqlite/files/107937/Sqlite.Repro.zip)

Simply execute "dnu restore && dnx run" to experience the issue.

**Comment by natemcmaster** [comment] 2016-02-03 20:15
This looks like it could be the same serializable bug we fixed in https://github.com/aspnet/Microsoft.Data.Sqlite/pull/213 (which is in build >= 15974). @gingters does your issue still occur with this fix?

**Comment by rowanmiller** [comment] 2016-02-16 19:28
Closing as we have not heard back

**Closed by rowanmiller** 2016-02-16 19:28 UTC

**Comment by natemcmaster** [comment] 2016-02-22 18:30
I found a similar, related issue for which I filed a fix in #232. This and #213 could have been the cause of the "database is locked" exceptions.
