### ISSUE TITLE
Support CommandBehavior.CloseConnection to ExecuteReader

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Microsoft.Data.Sqlite#142] opened 2015-09-17 23:27 UTC
Currently we only support `CommandBehavior.Default` and `CommandBehavior.SequentialAccess`.

Add support for `CommandBehavior.CloseConnection` to `SqliteDataReader.ExecuteReader(CommandBehavior behavior)`

**Comment by divega** [comment] 2015-09-19 22:11
:+1: dupe of #114?

**Comment by divega** [comment] 2015-09-19 22:14
Ah, I guessed you created this new bug because you already submitted a fix for the SequentiaAccess of #114 and you plan to close that bug.

**Comment by divega** [comment] 2015-09-19 22:16
I don't think this is lower priority so cleared up the milestone to bring it back to triage.

**Closed** 2015-11-05 00:23 UTC
Labels: pri0
