### ISSUE TITLE
Integer constant in CASE cuts decimal field values

### ISSUE THREAD

**Issue by igor-tkachev** [aspnet/Microsoft.Data.Sqlite#438] opened 2017-10-06 04:13 UTC
Table:

```sql
CREATE TABLE LinqDataTypes
(
	ID             int,
	MoneyValue     decimal(10,4)
);
```
The following query works just fine and returns
5.1, 10.22, 11.333

```sql
		SELECT
			CASE
				WHEN [t1].[MoneyValue] > 5.1
					THEN [t1].[MoneyValue]
				ELSE 5.1
			END as [c1]
		FROM
			[LinqDataTypes] [t1]
```

Next one cuts decimal values and returns
5, 10, 11

should be 
5, 10.22, 11.333

```sql
		SELECT
			CASE
				WHEN [t1].[MoneyValue] > 5
					THEN [t1].[MoneyValue]
				ELSE 5
			END as [c1]
		FROM
			[LinqDataTypes] [t1]
```

**Comment by smitpatel** [comment] 2017-10-06 17:27
This may be arising due to picking up data type from first row. Which in 2nd case is integer.

**Comment by igor-tkachev** [comment] 2017-10-06 18:10
This is a test from linq2db. It works for old SQLite and all other databases.

**Comment by bricelam** [comment] 2017-10-09 18:40
How are the values being read? `SqliteDataReader.GetFieldValue<decimal>()`?

**Comment by igor-tkachev** [comment] 2017-10-10 13:49
As I remember either IDataReader.GetDecimal(n) or IDataReader.GetValue(n).

**Comment by bricelam** [comment] 2018-01-05 22:38
I need more information to reproduce this. Do you have the full repro code?

**Comment by ajcvickers** [comment] 2018-01-12 19:46
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2018-01-12 19:46 UTC
Labels: type-investigation
