### ISSUE TITLE
ARM attempt error to load

### ISSUE THREAD

**Issue by glararan** [aspnet/Microsoft.Data.Sqlite#227] opened 2016-02-15 10:15 UTC
Hi,

First error that came when I build and run project on Windows IoT was this error:

> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module
> could not be found. (Exception from HRESULT: 0x8007007E)
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v
> 2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.open_v2(IntPtr
>  filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filenam
> e, Sqlite3Handle& ppDb, Int32 flags, String vfs)
>    at Microsoft.Data.Sqlite.SqliteConnection.Open()
>    at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
>    at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
>    at Microsoft.Data.Entity.Storage.Internal.SqliteDatabaseCreator.Exists()
>    at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureCreated()
>    at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
>    at DaisyWebControl.Startup.ConfigureServices(IServiceCollection services)

Then when I put sqlite3 for ARM from dir "C:\Users\glara\.dnx\packages\Microsoft.Data.Sqlite\1.0.0-rc2-15948\build\netcore50\win10-arm\native" into "C:\Windows\System32" on MS IoT

> System.DllNotFoundException: Unable to load DLL 'sqlite3': This operation is onl
> y valid in the context of an app container. (Exception from HRESULT: 0x8007109A)
> 
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.sqlite3_open_v
> 2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.Sqlite3_sqlite3.open_v2(IntPtr
>  filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
>    at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filenam
> e, Sqlite3Handle& ppDb, Int32 flags, String vfs)
>    at Microsoft.Data.Sqlite.SqliteConnection.Open()
>    at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
>    at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
>    at Microsoft.Data.Entity.Storage.Internal.SqliteDatabaseCreator.Exists()
>    at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureCreated()
>    at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
>    at DaisyWebControl.Startup.ConfigureServices(IServiceCollection services)

Thanks for any help!

**Comment by bricelam** [comment] 2016-02-16 18:05
You're trying to use the UWP assembly outside of a UWP app. (i.e. a container) You'll need to manually compile a non-UWP, ARM version of sqlite3.dll.

This is the same issue discussed in #187. Closing as a dupe.

**Closed by bricelam** 2016-02-16 18:05 UTC

**Comment by glararan** [comment] 2016-02-16 20:22
Ok is there some tutorial how to compile ARM version on x64?

**Comment by bricelam** [comment] 2016-02-16 21:41
@matizk144 might know. @timdows was also asking.

**Comment by bricelam** [comment] 2016-02-16 21:44
There might be some info buried under https://www.sqlite.org/cgi/src/

**Comment by glararan** [comment] 2016-02-16 21:46
There is no way how to contact user on github.. :(

**Comment by matizk144** [comment] 2016-02-18 08:35
Hello
> Unable to load DLL 'sqlite3': This operation is only valid in the context of an app container

The problem is about compilation of sqlite3.dll. As default, dll was compiled pod UWP.
Please download sources from my repo
https://github.com/matizk144/SqlLite3
and compile as ARM. Try replace dll to compiled dll.

> Unable to load DLL 'sqlite3': The specified module could not be found

This is another problem, that Microsoft.Data.SqlLite cannot see dll. Try copy sqlite.dll to directory, where Microsoft.Data.SqlLite.dll exists

**Comment by glararan** [comment] 2016-02-18 15:14
Ok thanks for help. I will try it in few days and i'll post response

**Comment by timdows** [comment] 2016-02-18 20:15
@glararan I have been able to work around this my on ARM environment (Raspberry PI2) by removing sqlite3 from the NativeMethodsImpl.tt. This forces the package to use the winsqlite3.dll which came preinstalled in c:\windows\system32 on my Windows 10 IoT installation

**Comment by glararan** [comment] 2016-02-18 20:29
I just now compiled sqlite from @matizk144 and its working I will also try yours version @timdows , @matizk144 I had to put sqlite.dll to c:/windows/system32, thanks btw!

**Comment by divega** [comment] 2016-02-18 21:37
> I have been able to work around this my on ARM environment (Raspberry PI2) by removing sqlite3 from the NativeMethodsImpl.tt. __This forces the package to use the winsqlite3.dll which came preinstalled in c:\windows\system32__ on my Windows 10 IoT installation

@natemcmaster @bricelam don't we have a method you can call to do that?

**Comment by bricelam** [comment] 2016-02-18 21:39
Yes, if you call `SqliteEngine.UseWinSqlite3()` during startup, `winsqlite3.dll` will be used.

**Comment by NickFessel** [comment] 2016-03-26 02:46
I found a quick workaround similar to @timdows's workaround. 

Copy the winsqlite3.dll from the c:\windows\system32 directory on the Win10 IoT device to the bin directory for the project on the Win10 IoT device. Then rename the winsqlite3.dll file to sqlite3.dll. 

My particular project directory where I copied winsqlite3.dll is approot\runtimes\dnx-coreclr-win-arm.1.0.0-rc1-final\bin, but your directory may differ depending on what arm version is in use for your particular project.

Sqlite is now functioning on my Raspberry Pi 3 thanks to this workaround. Thanks @timdows for the information.

**Comment by natemcmaster** [comment] 2016-03-26 03:10
@NickFessel does `SqliteEngine.UseWinSqlite3()` not work?

**Comment by NickFessel** [comment] 2016-03-26 12:36
@natemcmaster Where does the string `SqliteEngine.UseWinSqlite3()` belong in the project? And do I need to add anything else other than `SqliteEngine.UseWinSqlite3()`? I tried putting `SqliteEngine.UseWinSqlite3()` in the constructor in startup.cs, but Visual Studio is not resolving it ('The name SqliteEngine does not exist in the current context').

**Comment by natemcmaster** [comment] 2016-03-26 18:05
@NickFessel this API was added in a few months ago, so it's not in the RC1 release. All recent nightly builds include it. Without this API, what you've done (copying winsqlite3.dll to the local bin folder & renaming) is the right workaround. See https://github.com/aspnet/Microsoft.Data.Sqlite/pull/186.
