### ISSUE TITLE
Save Memory Db to file

### ISSUE THREAD

**Issue by glcjr** [aspnet/Microsoft.Data.Sqlite#469] opened 2017-12-21 22:12 UTC
Is there a sample for saving a database that was started as an in memory one to a file? I looked elsewhere and found a command BackUpDatabase but it doesn't appear to be implemented in this library. Is there another way?

**Comment by bricelam** [comment] 2017-12-21 23:57
Backup API is coming in 2.1. Until then, you can use the backup API in SQLitePCL.raw directly.

**Comment by glcjr** [comment] 2017-12-22 00:11
Thanks bricelam!

**Comment by bricelam** [comment] 2017-12-22 23:15
Duplicate of #17

**Closed by bricelam** 2017-12-22 23:15 UTC
