### ISSUE TITLE
Revert "Revert "Implement SqliteCommand.Prepare.""

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Microsoft.Data.Sqlite#345] opened 2017-03-24 20:19 UTC
Revert the PR #344 after investigating the downstream failures it caused. See https://github.com/aspnet/EntityFramework/issues/7982

**Comment by bricelam** [comment] 2017-03-25 00:05
Note to self: we probably need to reset the statement immediately after we're done reading it.

**Comment by AlexanderTaeschner** [comment] 2017-03-26 20:37
Unfortunately I am not able to reproduce the failures on my local machine, so that I cannot help here.

**Comment by bricelam** [comment] 2017-05-01 22:05
Re-opening #235 and closing this as a dupe.

**Closed by bricelam** 2017-05-01 22:05 UTC
Labels: type-enhancement
