### ISSUE TITLE
Keyword not supported: 'password'.

### ISSUE THREAD

**Issue by Aristarh71** [aspnet/Microsoft.Data.Sqlite#453] opened 2017-11-03 08:15 UTC
It's not possible to connect to password encrypted file.
I use connection string like "Data Source=C:\DataBaseFiles\Sqlite\TestDataEncrypted.db;Password=123".
Here is my database file:
[TestDataEncrypted.zip](https://github.com/aspnet/Microsoft.Data.Sqlite/files/1440395/TestDataEncrypted.zip)
I got error on Windows, on Linux it works fine.

**Comment by bricelam** [comment] 2017-11-03 17:37
Possible duplicate of #401.

Microsoft.Data.Sqlite doesn't support the `Password` keyword. See [the sample](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/EncryptionSample/Program.cs) and [this blog post](http://www.bricelam.net/2016/06/13/sqlite-encryption.html) for how to use encryption with Microsoft.Data.Sqlite version 2.0.0+

**Closed** 2017-11-10 19:45 UTC
