### ISSUE TITLE
Native libs don't get copied using indirect package references

### ISSUE THREAD

**Issue by TechnikEmpire** [aspnet/Microsoft.Data.Sqlite#458] opened 2017-11-25 22:52 UTC
I have a .NET Standard 2.0 library that references and uses this package. If I then reference my package, which references this one, the native libs in the `x64` and `x86` directories are never copied. IIRC they don't even get copied when building my library, which directly references. I have to explicitly add this package to a project with an executable output in order to see those native libs get copied to the out dir.

Tooling/runtime deets:  
![image](https://user-images.githubusercontent.com/11234763/33235610-5a9f776a-d209-11e7-9830-666cf825c7ef.png)

**Comment by ericsink** [comment] 2017-11-27 05:31
I believe this is expected behavior.

In general, yes, you have to reference the package from your actual app/exe project in order to get the native platform-specific stuff handled properly.  This is normal behavior for packages that use the so-called bait-and-switch trick to handle platform-specific stuff.

Although, actually, I just tried a case involving .NET Core, and the behavior seems different.  I created a .NET Standard 2.0 library, and then a .NET Core 2.0 console app.  The lib references SQLitePCLRaw.bundle_e_sqlite3, and the app references only the library project.  Running the app seems to work.  This suggests that the behavior of native platform-specific things in a transitive reference is being done differently, but I don't know if the key difference is .NET Core or merely PackageReference.

**Comment by TechnikEmpire** [comment] 2017-11-27 05:35
Well it seems counterintuitive that programs referencing my nuget package which explicitly depends on this package need to find this package manually in nuget and add it. And they won't know they need to do this until they try to run the program and it explodes the universe.

I have another .net core project where I consistently handle copying native libs to the end user application by incorporating a targets file to handle that. If anyone would like I could implement that here and do a pr.

**Comment by TechnikEmpire** [comment] 2017-11-27 05:38
Btw the user figuring it out and manually adding via nuget is best case scenario. In truth most people will go to use my library and when it explodes just shrug and dismiss it as another junk package written by yet another pretend programmer. Methinks this isn't proper behavior.

**Comment by ericsink** [comment] 2017-11-27 05:38
Just to be clear, what platform/configuration is being used in the project you mention in the original post, the one where you see the problem?

**Comment by TechnikEmpire** [comment] 2017-11-27 05:40
@ericsink Yeah I filed this quickly and didn't give any repro info.

.Net Standard 2.0 library references this library.
Create .NET Standard or .NET full (4.6.1 or greater) console app, add my lib via nuget.
Compile, boom no native libs for sqlite copied to console app bin dir (x86/x64 dirs + contents).

**Comment by ericsink** [comment] 2017-11-27 05:40
And I should also clarify:  I am not one of the maintainers of Microsoft.Data.Sqlite, and I'm not speaking for them.  I just thought I would chime in to try and help.

(I *do* maintain SQLitePCL.raw, which is a dependency of Microsoft.Data.Sqlite.)

**Comment by TechnikEmpire** [comment] 2017-11-27 05:41
@ericsink Gotcha, appreciate your input.

**Comment by ericsink** [comment] 2017-11-27 05:44
OK, so if the console app is .NET Framework (.NET full, .NET classic, whatever), then my claim that this behavior is expected (albeit lamentable) does apply.  Or rather, I should just say it this way:  For that configuration, the behavior you describe does not surprise me.

Like I said above, it does seem to me that a .NET Core project handles the transitive reference in a "better" way.

One thing I haven't tried, but am curious about:  What would happen with a .NET Framework project, but using PackageReference in the csproj, instead of packages.config?  AFAIK, this requires hand editing the csproj, so it's not of help in addressing usability issues.  I'm just curious.

**Comment by TechnikEmpire** [comment] 2017-11-27 05:49
I'm sure it is "normal" behavior with current tooling I'm just saying it
probably shouldn't be. It makes no sense that I only get half the package
payload with an indirect reference. It doesn't surprise me because I had to
manually fix this in one of my projects.

You're right on the money in terms of editing csproj directly and there's a
Microsoft article about doing this .net standard libs. You edit the csproj
and manually incorporate a targets file that handles ensuring native libs
get copied to end user project.

If they want a pr I can do it in no time.

**Comment by TechnikEmpire** [comment] 2017-11-27 05:55
Example of the above described modifications:

https://github.com/TechnikEmpire/CitadelCore.Windows/blob/master/CitadelCore.Windows/CitadelCore.Windows/build/CitadelCore.Windows.targets

https://github.com/TechnikEmpire/CitadelCore.Windows/blob/master/CitadelCore.Windows/CitadelCore.Windows/CitadelCore.Windows.csproj

The targets file and the modifications on the tail end of the csproj ensure that the bundled native libs get copied properly.

**Comment by bricelam** [comment] 2017-11-27 17:41
> I'm sure it is "normal" behavior with current tooling I'm just saying it
probably shouldn't be.

Agreed. We passed this along to the NuGet team a while ago (NuGet/Home#5841), but it wasn't enough to change the design or allow for exceptions.

**Comment by TechnikEmpire** [comment] 2017-11-27 17:47
@bricelam Thanks for the link to the external issue. You can overcome this limitation with a targets file and modifications to the csproj, I've linked to how I've accomplished this with my own .NET standard lib that bundles pinvoked native libraries. Anyway thanks for looking into it either way.

**Comment by ericsink** [comment] 2017-11-27 17:51
FWIW, SQLitePCL.raw *does* use the targets file technique in some cases.  I haven't looked closely at the example you linked, but my experience in this area tells me to be skeptical about a simple fix.  SQLitePCL.raw covers a lot of different platforms.

**Comment by TechnikEmpire** [comment] 2017-11-27 18:02
Well the fix is a documented one. It's right in official Ms articles about bundling targets into your project and nuget package. I certainly didn't come here trying to advertise garbage that doesn't work. The solution works and it's documented by Microsoft. Anyway take it or leave it.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

Related data is on the same page and not necessarily all at the heading I linked to.

**Comment by ericsink** [comment] 2017-11-27 18:33
No offense was intended.  :-)

I am familiar with the docs you linked.  Cheers.

**Comment by toddlang** [comment] 2017-11-29 14:44
I *think* this discussion is related to the problem I'm currently having, but I'm not sure what the answer is here.

I have a ASP.NET Core MVC application that consumes a .Net Core library that references the SQLite package. (Microsoft.Data.Sqlite.Core 2.0.0)

That can consume and utilize the library quite happily, generating databases with a connection string of "Data Source=webapp.sqlite3;"  However, then created a xUnit Core Test Library, referenced my library and tried to call some of the methods and I get "You need to call SQLitePCL.raw.SetProvider()...".   

So, I'm wondering what's causing the difference between the two usages of the library.  Both consume the SQLite package indirectly, specifically via the reference to the library I have that exposes the functionality.  Is it because the test library has no real application "context"?  (I'm grasping at straws here...)

**Comment by bricelam** [comment] 2017-11-29 17:15
@toddlang If you add `SQLitePCLRaw.bundle_green` to the projects, does the problem go away? If not, this is probably a different issue.

**Comment by bricelam** [comment] 2017-11-29 17:19
Actually, you're probably hitting a similar but different MSBuild quirk. Since `SQLitePCLRaw.batteries_v2.dll` isn't used by your class library, MSBuild won't transitively copy it into projects that reference your class library.

**Comment by toddlang** [comment] 2017-11-29 18:04
It's unusual that it works from the MVC app, but not from the test library then, no?  Not sure how to go about adding that SQLitePCLRaw to the project.  I just imported the Nuget package and went to town...works for the app, not for the test library.

**Comment by bricelam** [comment] 2017-12-04 20:32
@toddlang If you want to submit a new issue with additional details (e.g. a repro project) I can investigate further.

Closing this issue as external to Microsoft.Data.Sqlite, since we've done everything we can using the NuGet features available to us.

**Closed by bricelam** 2017-12-04 20:32 UTC
Labels: closed-external, type-investigation
