### ISSUE TITLE
NullRef exception while opening SqliteConnection using 1.0.0-rc1-16048

### ISSUE THREAD

**Issue by sady4850** [aspnet/Microsoft.Data.Sqlite#164] opened 2015-10-30 08:21 UTC
It worked with 1.0.0-rc1-15838

Repro:
```
            var connection = new SqliteConnection("Data Source=nwind.db");
            connection.Open();
```

System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.Interop.NativeMethods' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at ConsoleApp5.Program.Main(String[] args) in D:\Applications\ConsoleApp5\src\ConsoleApp5\Program.cs:line 14
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()

**Comment by natemcmaster** [comment] 2015-10-30 17:14
Duplicate of #128 ?

**Closed** 2015-10-30 18:52 UTC
