### ISSUE TITLE
CoreCLR on Linux: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0'

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Microsoft.Data.Sqlite#133] opened 2015-09-03 20:28 UTC
dnx-coreclr-linux-x64.1.0.0-beta7
Microsoft.Data.SQLite.1.0.0-beta7-15015

[Travis log](https://travis-ci.org/AlekseyMartynov/LimeBean-dnx-beta7/builds/78644839#L2477)

https://github.com/aspnet/Microsoft.Data.Sqlite/commit/56dd33cee3886c38643bf2c31cb9bafccfdb305a was not enough?

**Comment by natemcmaster** [comment] 2015-09-03 22:52
Duplicate of #121. Fixed with #123 

This is a known issue in beta7 (see https://github.com/aspnet/Home/releases/tag/v1.0.0-beta7)

**Closed by natemcmaster** 2015-09-03 22:52 UTC
