### ISSUE TITLE
SQLite + EntityFrameworkCore = System.Reflection.MemberInfo.get_MetadataToken()

### ISSUE THREAD

**Issue by UppaJung** [aspnet/Microsoft.Data.Sqlite#277] opened 2016-07-15 15:48 UTC
```
public class DeviceKey
{
        [Key]
        public string Key { get; set; }

        public int ParticipantId { get; set; }

        public DeviceKey()
        {
        }

        public static async Task<DeviceKey> GetAsync(ScreenTimeContext dbContext)
        {
            return await
                (from r in dbContext.DeviceKeys
                 select r)
                 .FirstOrDefaultAsync();
        }
}
```

The query in GetAsync results in the following exception:

Exception:
System.InvalidOperationException

The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information."

at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Platform: UWP (running via a compile to x86)

    "Microsoft.ApplicationInsights": "2.1.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.2.3",
    "Microsoft.ApplicationInsights.WindowsApps": "1.1.1",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
    "Newtonsoft.Json": "9.0.1"

**Comment by natemcmaster** [comment] 2016-07-15 16:40
Duplicate of https://github.com/aspnet/EntityFramework/issues/6088

**Closed by natemcmaster** 2016-07-15 16:40 UTC
Labels: closed-duplicate
