### ISSUE TITLE
Reader.GetBytes is not supported yet, or will never be ? 

### ISSUE THREAD

**Issue by BeeDi** [aspnet/Microsoft.Data.Sqlite#206] opened 2015-12-21 15:28 UTC
Hello, 
I am wondering if the GetBytes will be supported one day, or if there is another way to read a Byte array in the meantime ? 

Thanks

**Comment by natemcmaster** [comment] 2015-12-21 20:05
GetBytes requires incremental blob I/O, which is a currently a backlog item (see https://github.com/aspnet/Microsoft.Data.Sqlite/issues/18.) You can workaround with `reader.GetFieldValue<byte[]>()`

Closing as a duplicate of #18

**Closed by natemcmaster** 2015-12-21 20:05 UTC

**Comment by BeeDi** [comment] 2015-12-30 17:45
Thanks :)
