### ISSUE TITLE
Apparent deadlock when combining transaction and triggers

### ISSUE THREAD

**Issue by MHHenriksen** [aspnet/Microsoft.Data.Sqlite#416] opened 2017-09-05 11:03 UTC
I'm using fts5 with a contentless table and triggers to update the index (https://sqlite.org/fts5.html#external_content_tables). It seems that there's something deadlocking, causing SQLITE_BUSY exception for all but one attempt, if more than one thread attempts to modify the table (using CREATE, UPDATE or DELETE), and only if each command is executed in a transaction.

I've made a gist to reproduce my issue: https://gist.github.com/MHHenriksen/b3edb0f4020e4c304b92463c3c9223a5

This is tested with Microsoft.Data.Sqlite 1.1.0, which uses Sqlite 3.13.0, but if I did it right I also reproduced it with 3.20.1.

I have a feeling that the deadlock is happening in the native sqlite library, and I know there's not much you can do about that. But one workaround is to use BEGIN IMMEDIATE, and I know you removed support for that a while back. Is this good enough reason to consider reintroducing it?

And can you help me figure out the root cause?

**Comment by MHHenriksen** [comment] 2017-09-06 12:23
Here's the sqlite-users message I've sent: https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg105480.html

I think I misremembered which version the BEGIN IMMEDIATE change was made, looks like it's #214 which only affects 2.0, so we can actually make use of IsolationLevel.Serialized since we're still running the 1.x release.

I am working on upgrading everything to .Net Core 2 though, so please consider reintroducing a way to use BEGIN IMMEDIATE. No rush, I have code in place to do it with plain commands already. :)

**Comment by bricelam** [comment] 2018-01-09 21:35
#474 may help this.

**Comment by bricelam** [comment] 2018-02-06 21:47
Duplicate of #474

We've reverted to using `BEGIN IMMEDIATE` with `IsolationLevel.Serialized`. Please let us know if the issue isn't resolved.

**Closed by bricelam** 2018-02-06 21:47 UTC
Labels: type-bug
