### ISSUE TITLE
IsolationLevel.ReadCommitted is unsupported

### ISSUE THREAD

**Issue by 303248153** [aspnet/Microsoft.Data.Sqlite#272] opened 2016-06-15 03:17 UTC
Just like the title, this driver report ReadCommitted is unsupported, but I can use ReadCommitted  with System.Data.Sqlite.
Also I saw the tests in this project use ReadUncommitted, is that mean Microsoft.Data.Sqlite only support ReadUncommited?

**Comment by bricelam** [comment] 2016-06-15 03:24
Dupe of #214

**Closed by bricelam** 2016-06-15 03:24 UTC
