### ISSUE TITLE
[Proposal] Make SqliteConnectionExtensions public

### ISSUE THREAD

**Issue by AlexanderTaeschner** [aspnet/Microsoft.Data.Sqlite#368] opened 2017-05-05 10:50 UTC
It would be nice to make SqliteConnectionExtensions public, so that constructs like
```csharp
    var command = _connection.CreateCommand();
    command.CommandText = "PRAGMA foreign_keys=ON;";
    command.ExecuteNonQuery();
    command.Dispose();
```
can be simplified to
```csharp
    _connection.ExecuteNonQuery("PRAGMA foreign_keys=ON;");
```

**Comment by bricelam** [comment] 2017-05-05 19:18
Dupe of #226

**Closed by bricelam** 2017-05-05 19:18 UTC
