### ISSUE TITLE
Unable to load 'sqlite3' on Win IoT (ARM)

### ISSUE THREAD

**Issue by matizk144** [aspnet/Microsoft.Data.Sqlite#187] opened 2015-12-05 21:34 UTC
Hi!
I just trying to run asp.net web api using kestrel on my RP2 (Windows IoT - ARM architecture) using sqllite dll. Unfortunatelly all tries was finished fails. Of course, problem doesn't occur on Windows x86 & x64.
Below part of stack trace:
Application startup exception: System.Reflection.TargetInvocationException: Exception has been th
rown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'sqlite
3': This operation is only valid in the context of an app container. (Exception from HRESULT: 0x8
007109A)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle&
 ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle&
 ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection c
onnection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteScalar(IRelationalConnectio
n connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFac
ade)
   at InteligentnyDom.WebApi.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, 
ILoggerFactory loggerFactory)

I predict, that the problem is related with isolated storage, which exists on WinRT or Win 10 Mobile (XAP & APPX packages), but how to use sqllite on RP2?

**Comment by bricelam** [comment] 2015-12-05 23:55
Hmm, I don't think SQLite publishes a non-WinRT ARM dll, but that's what you need...

**Comment by bricelam** [comment] 2015-12-05 23:56
Oh, maybe you can use winsqlite3.dll. See #186

**Comment by bricelam** [comment] 2015-12-06 00:00
@moozzyk Will DNX load from `C:\Windows\System32`? It's on the path.

**Comment by moozzyk** [comment] 2015-12-06 19:24
I guess if it is APPX it does not have access to anything outside the package.

**Comment by matizk144** [comment] 2015-12-07 17:15
**bricelan** said:
> Oh, maybe you can use winsqlite3.dll. See #186

In which branch can I use winsqlite3.dll? I don't see any class and any methods in official repository to use it. I've only seen commit in **bricelan** fork, but now it's not available.

**moozzyk** said:
> I guess if it is APPX it does not have access to anything outside the package.

Could you tell me, what about non-APPX applications? How should I use it?

Btw. I don't use sqlite directly. *EntityFramework.Sqlite* packages use it.

**Comment by bricelam** [comment] 2015-12-07 18:22
@moozzyk This is DNX on ARM. No APPX as far as I understand it.
@matizk144 It's sill just a PR/fork. I'll merge it sometime this week after which it will be in the nightly builds.

**Comment by moozzyk** [comment] 2015-12-07 20:50
Then `LoadLibrary` should be able to find any dll that is in a folder that is on the path (including System32 which is on the path by default). If it can't it probably means that it is either an invalid dll (e.g. the dll architecture does not match the process architecture) or one of the dependencies cannot be load. Trying loading the dll with `LoadLibrary` can tell you if the issue is with DNX or the dll itself.

**Comment by matizk144** [comment] 2015-12-08 21:14
I created vnext console application and tried to load sqlite3.dll directly. To load dlls I used two approach:
- DllImport (the same, what it's in the sqlite repository)
- LoadLibrary, GetProcAddress

I tested some cases, using coreclr and procesor architectures:
- on computer (x86 & x64)
- RP2 (ARM)

To test dll caller I used method sqlite3_libversion and MarshalEx.PtrToStringUTF8 converted, which exist in Microsoft.Data.Sqlite repository.
Additionaly I must to tell that in nuget Sqlite package we had two kinds of dlls:
- Windows 7 (win7-x86, win7-x64)
- Windows 10 (win10-arm, win10-x86, win10-x64)

Computer:
When I tried to use dll (in both architectures: x86 & x64) using
- Windows 7 dlls - it works
- Windows 10 dlls - This operation is only valid in the context of an app container (error reproduced, which I have on RPi2)

So, now I know, that in my computer (in fact Windows 10), sqlite use Windows7 dlls. Maybe, it's related, because I not create APPX applications.
Unfortunately in nuget package dlls for ARM is missing :(

Then I tested, what's going using loadlibrary, GetProcAddress:
- Windows 7 dlls (method loadlibrary loads dll, GetProcAddress loads method)
- Windows 10 dlls (loadlibrary method cannot load dll)

I tried to use loadlibrary approach in RPi2 too, but the effect is the same (of course, trying load Win10-arm).

Finally I downloaded sourcecodes of sqlite and compiled it (x86, x64, ARM). But compilation generated new problems, that sqlite was written in ansi-c.
Unfortunately native sqlite methods is not visible in compilted dll, but dll was loaded in RPi2 (using loadlibrary method).

On all architectures compiled dll is loaded but GetProcAddress returns 0.
The same effect I have using dllimport: Unable to find an entry point named sqlite3_libversion


So, probably for me, I need dll like win7-arm. I can to prepare dll myself, but how to bind native methods, compiled in ansi-c in c#?

**Comment by moozzyk** [comment] 2015-12-08 23:10
I guess the difference between win7- and win10- dlls is what they are linked against. win7- is linked against the standard runtime (i.e. it depends on kernel32 and advapi32) while the win10- versions are linked against one core (i.e. the dll depends on forwarders instead of kernel32 and advapi32 directly). I have not played with universal native apps but remember seeing that there were two libs to link against on onecore - oncore.lib and onecoreuap.lib. I wonder if the message ("This operation is only valid in the context of an app container") is not a result of using a dll linked against onecoreuap.lib in a non native app. 
FWITW you can run dlls compiled against standard runtime (i.e. depending on kernel32.dll et. al) on Raspberry PI2 since Win10 IoT Core has reverse forwarders installed by default. Obviously you need to compile for ARM.
I don't think ANSI-C has anything to do with binding to native methods. In fact it may make it even easier since the exported names won't be mangled. You can use `dumpbin /exports {dllname}` to check what functions are exported from a dll and what their names are. If you don't see anything - maybe you missed a .def file when compiling?

**Comment by matizk144** [comment] 2015-12-09 20:31
Finally it's works. Thanks @moozzyk and @bricelam  for help. I downloaded precompiled binary for windows, which include .def file. Then I included this file into linker in sqlite ansi-c project and compiled for ARM. All things works correctly (with migrations too). If somebody want to have this dll I can to share it, whether I prepare own fork with this sqlite.dll

**Comment by moozzyk** [comment] 2015-12-09 20:33
@matizk144 :clap:

**Comment by timdows** [comment] 2016-01-08 10:55
@matizk144 would love to get your compiled sqlite3 as unfortunately I've encountered the same issue " Unable to load DLL 'sqlite3': The specified module could not be found." on my Raspberry PI 2

**Comment by rowanmiller** [comment] 2016-01-12 19:43
We don't want to be in the business of compiling custom builds of SQLite. If the SQLite team starts distributing an ARM version then we would add it into our package.

**Closed by rowanmiller** 2016-01-12 19:43 UTC
