### ISSUE TITLE
UWP Microsoft.Data.Sqlite Message = "SQLite Error 14: 'unable to open database file'."

### ISSUE THREAD

**Issue by rakismelange** [aspnet/Microsoft.Data.Sqlite#543] opened 2018-08-12 21:37 UTC
While developing a desktop application in UWP been getting this
Message = "SQLite Error 14: 'unable to open database file'."

Found out that UWP is forcing you to use the local storage:
https://stackoverflow.com/questions/37377183/cant-open-create-db-file-with-sqlite-in-visual-studio-uwp-c

This request is to setup SQLite to use "StorageFile APIs" so I can access db files outside the local storage area.

Also used "broadFileSystemAccess", it still doesn't work.

Why wouldn't Microsoft.Data.Sqlite honor that declaration?

**Comment by bricelam** [comment] 2018-08-13 16:29
Duplicate of #287

😟 Very sad to hear that broadFileSystemAccess doesn't help.

**Comment by bricelam** [comment] 2018-08-13 16:37
@praeclarum any breakthroughs in this area with SQLite-net?

**Closed** 2018-08-17 20:16 UTC
Labels: closed-duplicate
